apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: marypearl/shippingservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: default
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
